export const myTaskMaster = [
    {id: 0, task: "do some laundry", freq: 0}, // i.e. there's basically always laundry to do
    {id: 1, task: "bring in the mail", freq: 1},
    {id: 2, task: "scoop the litterboxes", freq: 1},
    {id: 3, task: "round up trash and recycling", freq: 1},
    {id: 4, task: "round up dirty dishes", freq: 1},
    {id: 5, task: "round up dirty laundry", freq: 1},
    {id: 6, task: "clean out the bathtub drain catch", freq: 1},
    {id: 7, task: "replace the dish rag", freq: 1},
    {id: 8, task: "take out the trash and recycling", freq: 1},
    {id: 9, task: "unload the dishwasher and the drying rack", freq: 2},
    {id: 10, task: "change the kitchen trash bag", freq: 2},
    {id: 11, task: "make the bed", freq: 2},
    {id: 12, task: "wipe down the kitchen counters", freq: 3},
    {id: 13, task: "vacuum the bedroom", freq: 3},
    {id: 14, task: "sweep in the living room, dining room, and hallway", freq: 3},
    {id: 15, task: "tidy in the art room", freq: 3},
    {id: 16, task: "clean the floors around the litterboxes", freq: 3},
    {id: 17, task: "empty the bedroom trash cans", freq: 4},
    {id: 18, task: "wipe down the stovetop", freq: 4},
    {id: 19, task: "empty the litter genie", freq: 4},
    {id: 20, task: "clean out the laundry room sink drain catch", freq: 4},
    {id: 21, task: "sweep and mop in the kitchen", freq: 5},
    {id: 22, task: "change the bathroom trash bag", freq: 7},
    {id: 23, task: "empty the art room trash can", freq: 7},
    {id: 24, task: "vacuum the art room", freq: 7},
    {id: 25, task: "vacuum in the living room", freq: 7},
    {id: 26, task: "clean the bathroom floors", freq: 7},
    {id: 27, task: "clean the bathroom sink", freq: 7},
    {id: 28, task: "clean the toilet", freq: 7},
    {id: 29, task: "clean the bathtub", freq: 7},
    {id: 30, task: "clean the inside of the microwave", freq: 7},
    {id: 31, task: "wipe down the outside of the kitchen appliances", freq: 7},
    {id: 32, task: "replace the bathroom hand towel", freq: 7},
    {id: 33, task: "clean and cycle the litter mats", freq: 7},
    {id: 34, task: "change the bedsheets", freq: 7},
    {id: 35, task: "clean the bathroom mirror", freq: 7},
    {id: 36, task: "dust in the artroom", freq: 7},
    {id: 37, task: "dust in the bedroom", freq: 7},
    {id: 38, task: "dust in the living room, dining room, and hallway", freq: 7},
    {id: 39, task: "tidy in the bedroom", freq: 7},
    {id: 40, task: "tidy in the living room and dining room", freq: 7},
    {id: 41, task: "wipe down the kitchen cabinet doors", freq: 11},
    {id: 42, task: "deep clean the stovetop", freq: 11},
    {id: 43, task: "vacuum the music room", freq: 11},
    {id: 44, task: "water my cactus", freq: 14},
    {id: 45, task: "replace the bathroom sink rag", freq: 14},
    {id: 46, task: "replace and wash the bath mats", freq: 14},
    {id: 47, task: "empty the living room trash can", freq: 14},
    {id: 48, task: "dust in the bathroom", freq: 14},
    {id: 49, task: "change the music room trash bag", freq: 14},
    {id: 50, task: "replace the kitchen hand and dish drying towels", freq: 21},
    {id: 51, task: "deep clean the bathroom sink hardware", freq: 21},
    {id: 52, task: "replace the laundry room hose", freq: 21},
    {id: 53, task: "clean out the bathroom sink drain", freq: 31},
    {id: 54, task: "clean the kitchen sink", freq: 31},
    {id: 55, task: "clean the laundry room sink", freq: 31},
    {id: 56, task: "replace the litter", freq: 31},
    {id: 57, task: "replace the laundry room trash bag", freq: 45},
    {id: 58, task: "clean the living room mirror", freq: 45},
];